### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by Heinzler** [merlinschumacher/python-pdf-ocr#1]
Ich bekomme immer die Fehlermeldung
  File "../../python-pdf-ocr/python-pdf-ocr.py", line 92
    `{self.extras.price}`"""

Woran könnte das liegen und wie kann ich das beheben?

**Comment by Geraldf** [comment]
Liegt wahrscheinlich an der Python Version. Mit V3.7.3 geht es.

**Comment by Heinzler** [comment]
Mit 3.7.3 hat es funktioniert.
